//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Hilt_Borrow_History
    {
        public int Id { get; set; }
        public string UserDepartment { get; set; }
        public string UserName { get; set; }
        public string KnifeDepartment { get; set; }
        public string KnifeName { get; set; }
        public string KnifeSpecification { get; set; }
        public int BorrowNumber { get; set; }
        public int ReturnNumber { get; set; }
        public int BadNumber { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string BorrowTime { get; set; }
        public string Remarks { get; set; }
        public string NewOldKnife { get; set; }
        public string project { get; set; }
    }
}
