//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_ToolHolder_Tool_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_ToolHolder_Tool_Table()
        {
            this.JDJS_WMS_Tool_Shank_Table = new HashSet<JDJS_WMS_Tool_Shank_Table>();
            this.JDJS_WMS_ToolHolder_ToolLife_History_Table = new HashSet<JDJS_WMS_ToolHolder_ToolLife_History_Table>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ToolHolderID { get; set; }
        public Nullable<int> ToolNum { get; set; }
        public string ToolName { get; set; }
        public Nullable<double> ToolLength { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> ToolSpecifications { get; set; }
        public Nullable<int> VerdorID { get; set; }
        public string Batch { get; set; }
        public Nullable<int> BladesNum { get; set; }
        public string Type { get; set; }
        public Nullable<double> BladeLength { get; set; }
        public Nullable<double> TheoryR { get; set; }
        public Nullable<double> RAngle { get; set; }
        public Nullable<double> EffectiveLength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Tool_Shank_Table> JDJS_WMS_Tool_Shank_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_ToolHolder_ToolLife_History_Table> JDJS_WMS_ToolHolder_ToolLife_History_Table { get; set; }
    }
}
