//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Device_Info()
        {
            this.JDJS_WMS_Device_Alarm_History_Table = new HashSet<JDJS_WMS_Device_Alarm_History_Table>();
            this.JDJS_WMS_Device_Alarm_Repair = new HashSet<JDJS_WMS_Device_Alarm_Repair>();
            this.JDJS_WMS_Device_Borrow_Info = new HashSet<JDJS_WMS_Device_Borrow_Info>();
            this.JDJS_WMS_Quality_Onmachine_Measurement_Data = new HashSet<JDJS_WMS_Quality_Onmachine_Measurement_Data>();
            this.JDJS_WMS_Device_ProgState_Info = new HashSet<JDJS_WMS_Device_ProgState_Info>();
            this.JDJS_WMS_Device_RealTime_Data = new HashSet<JDJS_WMS_Device_RealTime_Data>();
            this.JDJS_WMS_Device_Reserve_Info = new HashSet<JDJS_WMS_Device_Reserve_Info>();
            this.JDJS_WMS_Device_Return_Info = new HashSet<JDJS_WMS_Device_Return_Info>();
            this.JDJS_WMS_Device_RunTime_Data = new HashSet<JDJS_WMS_Device_RunTime_Data>();
            this.JDJS_WMS_Device_Times_Data = new HashSet<JDJS_WMS_Device_Times_Data>();
            this.JDJS_WMS_Device_Tool_History_Table = new HashSet<JDJS_WMS_Device_Tool_History_Table>();
            this.JDJS_WMS_Device_UtilizationRate = new HashSet<JDJS_WMS_Device_UtilizationRate>();
            this.JDJS_WMS_Maintenance_Plan_Table = new HashSet<JDJS_WMS_Maintenance_Plan_Table>();
            this.JDJS_WMS_Order_Process_Scheduling_Table = new HashSet<JDJS_WMS_Order_Process_Scheduling_Table>();
            this.JDJS_WMS_Quickchangbaseplate_Table = new HashSet<JDJS_WMS_Quickchangbaseplate_Table>();
            this.JDJS_WMS_Tool_LifeTime_Management = new HashSet<JDJS_WMS_Tool_LifeTime_Management>();
            this.JDJS_WMS_Tool_LifeTimeOver_History_Table = new HashSet<JDJS_WMS_Tool_LifeTimeOver_History_Table>();
            this.JDJS_WMS_Tool_Shank_Table = new HashSet<JDJS_WMS_Tool_Shank_Table>();
            this.JDJS_WMS_ToolChangeMessage_Issued_Table = new HashSet<JDJS_WMS_ToolChangeMessage_Issued_Table>();
        }
    
        public int ID { get; set; }
        public string MachNum { get; set; }
        public string IP { get; set; }
        public string MachState { get; set; }
        public int MachType { get; set; }
        public Nullable<int> Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Alarm_History_Table> JDJS_WMS_Device_Alarm_History_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Alarm_Repair> JDJS_WMS_Device_Alarm_Repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Borrow_Info> JDJS_WMS_Device_Borrow_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_Onmachine_Measurement_Data> JDJS_WMS_Quality_Onmachine_Measurement_Data { get; set; }
        public virtual JDJS_WMS_Location_Info JDJS_WMS_Location_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_ProgState_Info> JDJS_WMS_Device_ProgState_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_RealTime_Data> JDJS_WMS_Device_RealTime_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Reserve_Info> JDJS_WMS_Device_Reserve_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Return_Info> JDJS_WMS_Device_Return_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_RunTime_Data> JDJS_WMS_Device_RunTime_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Times_Data> JDJS_WMS_Device_Times_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Tool_History_Table> JDJS_WMS_Device_Tool_History_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_UtilizationRate> JDJS_WMS_Device_UtilizationRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Maintenance_Plan_Table> JDJS_WMS_Maintenance_Plan_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Process_Scheduling_Table> JDJS_WMS_Order_Process_Scheduling_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quickchangbaseplate_Table> JDJS_WMS_Quickchangbaseplate_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Tool_LifeTime_Management> JDJS_WMS_Tool_LifeTime_Management { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Tool_LifeTimeOver_History_Table> JDJS_WMS_Tool_LifeTimeOver_History_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Tool_Shank_Table> JDJS_WMS_Tool_Shank_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_ToolChangeMessage_Issued_Table> JDJS_WMS_ToolChangeMessage_Issued_Table { get; set; }
    }
}
