//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Users_Login_Info
    {
        public int Id { get; set; }
        public string Users { get; set; }
        public string PassWords { get; set; }
        public Nullable<int> Limit { get; set; }
    }
}
