//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_Maintenance_Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Device_Maintenance_Status()
        {
            this.JDJS_WMS_Device_Alarm_Repair = new HashSet<JDJS_WMS_Device_Alarm_Repair>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DescID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Device_Alarm_Repair> JDJS_WMS_Device_Alarm_Repair { get; set; }
    }
}
