//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Order_Entry_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Order_Entry_Table()
        {
            this.JDJS_WMS_Blank_Additional_History_Table = new HashSet<JDJS_WMS_Blank_Additional_History_Table>();
            this.JDJS_WMS_Blank_Table = new HashSet<JDJS_WMS_Blank_Table>();
            this.JDJS_WMS_Finished_Product_In_History_Manager = new HashSet<JDJS_WMS_Finished_Product_In_History_Manager>();
            this.JDJS_WMS_Finished_Product_Manager = new HashSet<JDJS_WMS_Finished_Product_Manager>();
            this.JDJS_WMS_Finished_Product_OutPut_History_Manager = new HashSet<JDJS_WMS_Finished_Product_OutPut_History_Manager>();
            this.JDJS_WMS_Order_Blank_Table = new HashSet<JDJS_WMS_Order_Blank_Table>();
            this.JDJS_WMS_Quality_Onmachine_Measurement_Data = new HashSet<JDJS_WMS_Quality_Onmachine_Measurement_Data>();
            this.JDJS_WMS_Quality_ManualInput_Measurement_Table = new HashSet<JDJS_WMS_Quality_ManualInput_Measurement_Table>();
            this.JDJS_WMS_Order_Process_Scheduling_Table = new HashSet<JDJS_WMS_Order_Process_Scheduling_Table>();
            this.JDJS_WMS_Quality_Confirmation_Table = new HashSet<JDJS_WMS_Quality_Confirmation_Table>();
            this.JDJS_WMS_Order_Guide_Schedu_Table = new HashSet<JDJS_WMS_Order_Guide_Schedu_Table>();
            this.JDJS_WMS_Order_Intention_History_Table = new HashSet<JDJS_WMS_Order_Intention_History_Table>();
            this.JDJS_WMS_Order_Process_Info_Table = new HashSet<JDJS_WMS_Order_Process_Info_Table>();
            this.JDJS_WMS_Order_Queue_Table = new HashSet<JDJS_WMS_Order_Queue_Table>();
            this.JDJS_WMS_Quality_Confirmation_History_Table = new HashSet<JDJS_WMS_Quality_Confirmation_History_Table>();
        }
    
        public int Order_ID { get; set; }
        public string Order_Number { get; set; }
        public string Order_Leader { get; set; }
        public string Product_Name { get; set; }
        public string Product_Material { get; set; }
        public int Product_Output { get; set; }
        public Nullable<System.DateTime> Order_Plan_Start_Time { get; set; }
        public Nullable<System.DateTime> Order_Actual_Start_Time { get; set; }
        public Nullable<System.DateTime> Order_Plan_End_Time { get; set; }
        public Nullable<System.DateTime> Order_Actual_End_Time { get; set; }
        public string Engine_Program_Manager { get; set; }
        public string Engine_Technology_Manager { get; set; }
        public string Engine_Status { get; set; }
        public string Order_State { get; set; }
        public Nullable<int> Engine_Program_ManagerId { get; set; }
        public Nullable<int> Engine_Technology_ManagerId { get; set; }
        public Nullable<int> Intention { get; set; }
        public Nullable<int> virtualProgPersId { get; set; }
        public Nullable<System.DateTime> virtualReturnTime { get; set; }
        public Nullable<int> craftPersonId { get; set; }
        public string craftPerson { get; set; }
        public string audit_Result { get; set; }
        public Nullable<int> ProofingORProduct { get; set; }
        public string program_audit_result { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> CtratPersonID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreatePersonID { get; set; }
        public string AuditResult { get; set; }
        public string AuditAdvice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Blank_Additional_History_Table> JDJS_WMS_Blank_Additional_History_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Blank_Table> JDJS_WMS_Blank_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Finished_Product_In_History_Manager> JDJS_WMS_Finished_Product_In_History_Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Finished_Product_Manager> JDJS_WMS_Finished_Product_Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Finished_Product_OutPut_History_Manager> JDJS_WMS_Finished_Product_OutPut_History_Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Blank_Table> JDJS_WMS_Order_Blank_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_Onmachine_Measurement_Data> JDJS_WMS_Quality_Onmachine_Measurement_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_ManualInput_Measurement_Table> JDJS_WMS_Quality_ManualInput_Measurement_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Process_Scheduling_Table> JDJS_WMS_Order_Process_Scheduling_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_Confirmation_Table> JDJS_WMS_Quality_Confirmation_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Guide_Schedu_Table> JDJS_WMS_Order_Guide_Schedu_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Intention_History_Table> JDJS_WMS_Order_Intention_History_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Process_Info_Table> JDJS_WMS_Order_Process_Info_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Order_Queue_Table> JDJS_WMS_Order_Queue_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_Confirmation_History_Table> JDJS_WMS_Quality_Confirmation_History_Table { get; set; }
    }
}
