//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Order_Process_Tool_Info_Table
    {
        public int ID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string PathName { get; set; }
        public Nullable<int> ToolNO { get; set; }
        public string ToolName { get; set; }
        public string Shank { get; set; }
        public Nullable<double> ToolLength { get; set; }
        public Nullable<double> ToolDiameter { get; set; }
        public Nullable<double> ToolAroidance { get; set; }
        public Nullable<int> isFine { get; set; }
        public Nullable<double> EffectiveLength { get; set; }
        public Nullable<double> BladeLenth { get; set; }
    
        public virtual JDJS_WMS_Order_Process_Info_Table JDJS_WMS_Order_Process_Info_Table { get; set; }
    }
}
