//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Quickchangbaseplate_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Quickchangbaseplate_Table()
        {
            this.JDJS_WMS_Blank_Table = new HashSet<JDJS_WMS_Blank_Table>();
            this.JDJS_WMS_Secondary_Tooling_Table = new HashSet<JDJS_WMS_Secondary_Tooling_Table>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CncID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Blank_Table> JDJS_WMS_Blank_Table { get; set; }
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Secondary_Tooling_Table> JDJS_WMS_Secondary_Tooling_Table { get; set; }
    }
}
