//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Maintenance_Plan_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Maintenance_Plan_Table()
        {
            this.JDJS_WMS_Maintenance_Confirm_Table = new HashSet<JDJS_WMS_Maintenance_Confirm_Table>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CncID { get; set; }
        public string MaintenanceContence { get; set; }
        public Nullable<System.DateTime> MaintenanceTime { get; set; }
        public Nullable<double> Cycle { get; set; }
        public Nullable<int> isFlag { get; set; }
        public string TimeStr { get; set; }
        public string MaintenanceName { get; set; }
        public Nullable<System.DateTime> start { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Maintenance_Confirm_Table> JDJS_WMS_Maintenance_Confirm_Table { get; set; }
    }
}
