//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Order_Files_Manage_Table
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string FileType { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string PersonName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> VersonNum { get; set; }
        public string UpdateOrCover { get; set; }
    }
}
