//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Warehouse_InOut_History_Table
    {
        public int ID { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<double> InNum { get; set; }
        public Nullable<double> OutNum { get; set; }
    }
}
