//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Tool_LifeTimeOver_History_Table
    {
        public int ID { get; set; }
        public Nullable<int> CncID { get; set; }
        public Nullable<int> ToolID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
    }
}
