//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Hilt_Stock_History
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string KnifeName { get; set; }
        public string KnifeSpecifications { get; set; }
        public Nullable<int> AllKnife { get; set; }
        public Nullable<int> NewKnife { get; set; }
        public Nullable<int> OldKnife { get; set; }
    }
}
