//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_Reserve_Info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Person { get; set; }
        public string Tel { get; set; }
        public string Team { get; set; }
        public Nullable<System.DateTime> BorrowTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public Nullable<System.DateTime> NowTime { get; set; }
        public Nullable<int> MachId { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
    }
}
