//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Device_RealTime_Data
    {
        public int ID { get; set; }
        public Nullable<double> MachCoord_X { get; set; }
        public Nullable<double> MachCoord_Y { get; set; }
        public Nullable<double> MachCoord_Z { get; set; }
        public Nullable<double> MachCoord_A { get; set; }
        public Nullable<double> MachCoord_B { get; set; }
        public Nullable<double> MachCoord_C { get; set; }
        public Nullable<double> AbsCoord_X { get; set; }
        public Nullable<double> AbsCoord_Y { get; set; }
        public Nullable<double> AbsCoord_Z { get; set; }
        public Nullable<double> AbsCoord_A { get; set; }
        public Nullable<double> AbsCoord_B { get; set; }
        public Nullable<double> AbsCoord_C { get; set; }
        public Nullable<double> RelCoord_X { get; set; }
        public Nullable<double> RelCoord_Y { get; set; }
        public Nullable<double> RelCoord_Z { get; set; }
        public Nullable<double> RelCoord_A { get; set; }
        public Nullable<double> RelCoord_B { get; set; }
        public Nullable<double> RelCoord_C { get; set; }
        public Nullable<int> ProgState { get; set; }
        public Nullable<int> CurrWCoord { get; set; }
        public Nullable<double> FeedRate { get; set; }
        public Nullable<int> SpindleSpeed { get; set; }
        public Nullable<int> ToolNo { get; set; }
        public Nullable<double> MachTime { get; set; }
        public Nullable<int> CurrO { get; set; }
        public Nullable<int> CurrOMainO { get; set; }
        public Nullable<int> CountNum { get; set; }
        public Nullable<int> SpindleRate { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<double> SInfo_A { get; set; }
        public Nullable<double> SInfo_NM { get; set; }
        public Nullable<double> SInfo_W { get; set; }
        public Nullable<int> CurLineNo { get; set; }
        public string CurLineText { get; set; }
        public Nullable<int> Time_Y { get; set; }
        public Nullable<int> Time_M { get; set; }
        public Nullable<int> Time_D { get; set; }
        public Nullable<int> Time_H { get; set; }
        public Nullable<int> Time_MIT { get; set; }
        public Nullable<int> Time_S { get; set; }
        public Nullable<int> Time_zone { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> CncID { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
    }
}
