//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Tool_Shanks_Specification_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Tool_Shanks_Specification_Table()
        {
            this.JDJS_WMS_Tool_Shank_Table = new HashSet<JDJS_WMS_Tool_Shank_Table>();
        }
    
        public int ID { get; set; }
        public string ToolShankSpecification { get; set; }
        public Nullable<int> ToolShankSpecificationNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Tool_Shank_Table> JDJS_WMS_Tool_Shank_Table { get; set; }
    }
}
