//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Quality_Apply_Measure_Table
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string WorkPieceName { get; set; }
        public string MeasureContent { get; set; }
        public string MeasureGoal { get; set; }
        public string DepartmentName { get; set; }
        public string ApplyPersonName { get; set; }
        public Nullable<int> ApplyPersonId { get; set; }
        public string ApplyPersonTel { get; set; }
        public Nullable<int> WorkPieceNum { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public Nullable<int> AcceptPersonId { get; set; }
        public string AcceptPersonName { get; set; }
        public string MeasureDevice { get; set; }
        public string MeasurePersonName { get; set; }
        public Nullable<int> MeasurePersonId { get; set; }
        public Nullable<System.DateTime> MeasureTime { get; set; }
        public string MeasureResult { get; set; }
        public Nullable<int> IsHaveReport { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> InspectTime { get; set; }
        public string SavePath { get; set; }
    }
}
