//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Scan_Operate_History_Table
    {
        public int ID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Operate { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> BlankID { get; set; }
        public Nullable<int> machID { get; set; }
        public Nullable<int> QuackPlateID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ToolID { get; set; }
        public Nullable<int> ShankID { get; set; }
        public string remarks { get; set; }
        public Nullable<int> MachToolNum { get; set; }
    }
}
