//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Tool_Standard_Table
    {
        public int ID { get; set; }
        public string ToolID { get; set; }
        public string Sort { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string ProcessStage { get; set; }
        public Nullable<double> RazorDiameter { get; set; }
        public Nullable<double> ToolDiameter { get; set; }
        public Nullable<double> ToolLength { get; set; }
        public Nullable<double> RotatingSpeed { get; set; }
        public Nullable<double> Feed { get; set; }
        public Nullable<double> Knife { get; set; }
        public string Shank { get; set; }
        public Nullable<int> MachTypeID { get; set; }
    
        public virtual JDJS_WMS_Device_Type_Info JDJS_WMS_Device_Type_Info { get; set; }
    }
}
