//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Tool_Shank_Table
    {
        public int ID { get; set; }
        public Nullable<int> ShankSpecificationID { get; set; }
        public Nullable<int> ShankNum { get; set; }
        public Nullable<int> ToolNum { get; set; }
        public Nullable<int> CncID { get; set; }
        public Nullable<int> ToolID { get; set; }
        public Nullable<double> ToolLength { get; set; }
        public Nullable<int> ToolStateFlag { get; set; }
        public Nullable<double> ToolRealR { get; set; }
        public Nullable<double> ToolTheoryR { get; set; }
        public Nullable<double> ToolJump { get; set; }
        public Nullable<int> ToolInfoFlag { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
        public virtual JDJS_WMS_Tool_Shanks_Specification_Table JDJS_WMS_Tool_Shanks_Specification_Table { get; set; }
        public virtual JDJS_WMS_ToolHolder_Tool_Table JDJS_WMS_ToolHolder_Tool_Table { get; set; }
    }
}
