//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Order_Process_Information_Table
    {
        public int ID { get; set; }
        public int ProcessID { get; set; }
        public string WorkMaterial { get; set; }
        public string XPoint { get; set; }
        public string YPoint { get; set; }
        public string ZPoint { get; set; }
        public string Note { get; set; }
    
        public virtual JDJS_WMS_Order_Process_Info_Table JDJS_WMS_Order_Process_Info_Table { get; set; }
    }
}
