//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JDJS_WMS_DB_USEREntities : DbContext
    {
        public JDJS_WMS_DB_USEREntities()
            : base("name=JDJS_WMS_DB_USEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JDJS_WMS_Blank_Additional_History_Table> JDJS_WMS_Blank_Additional_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Blank_Table> JDJS_WMS_Blank_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Chuck_Borrow_History> JDJS_WMS_Chuck_Borrow_History { get; set; }
        public virtual DbSet<JDJS_WMS_Chuck_Scrap_History> JDJS_WMS_Chuck_Scrap_History { get; set; }
        public virtual DbSet<JDJS_WMS_Chuck_Stock_Info> JDJS_WMS_Chuck_Stock_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Chuck_Storage_History> JDJS_WMS_Chuck_Storage_History { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Alarm_Description> JDJS_WMS_Device_Alarm_Description { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Alarm_History_Table> JDJS_WMS_Device_Alarm_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Alarm_Repair> JDJS_WMS_Device_Alarm_Repair { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Borrow_Info> JDJS_WMS_Device_Borrow_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Brand_Info> JDJS_WMS_Device_Brand_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Info> JDJS_WMS_Device_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Maintenance_Status> JDJS_WMS_Device_Maintenance_Status { get; set; }
        public virtual DbSet<JDJS_WMS_Device_ProgState_Info> JDJS_WMS_Device_ProgState_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_RealTime_Data> JDJS_WMS_Device_RealTime_Data { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Reserve_Info> JDJS_WMS_Device_Reserve_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Return_Info> JDJS_WMS_Device_Return_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_RunTime_Data> JDJS_WMS_Device_RunTime_Data { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Status_Table> JDJS_WMS_Device_Status_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Times_Data> JDJS_WMS_Device_Times_Data { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Tool_History_Table> JDJS_WMS_Device_Tool_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Type_Info> JDJS_WMS_Device_Type_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Device_UtilizationRate> JDJS_WMS_Device_UtilizationRate { get; set; }
        public virtual DbSet<JDJS_WMS_Device_Working_Process_Table> JDJS_WMS_Device_Working_Process_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Finished_Product_In_History_Manager> JDJS_WMS_Finished_Product_In_History_Manager { get; set; }
        public virtual DbSet<JDJS_WMS_Finished_Product_Manager> JDJS_WMS_Finished_Product_Manager { get; set; }
        public virtual DbSet<JDJS_WMS_Finished_Product_OutPut_History_Manager> JDJS_WMS_Finished_Product_OutPut_History_Manager { get; set; }
        public virtual DbSet<JDJS_WMS_Fixture_Additional_History_Table> JDJS_WMS_Fixture_Additional_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Fixture_Borrow_History> JDJS_WMS_Fixture_Borrow_History { get; set; }
        public virtual DbSet<JDJS_WMS_Fixture_Scrap_History> JDJS_WMS_Fixture_Scrap_History { get; set; }
        public virtual DbSet<JDJS_WMS_Fixture_Stock_Info> JDJS_WMS_Fixture_Stock_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Fixture_Storage_History> JDJS_WMS_Fixture_Storage_History { get; set; }
        public virtual DbSet<JDJS_WMS_Hilt_Borrow_History> JDJS_WMS_Hilt_Borrow_History { get; set; }
        public virtual DbSet<JDJS_WMS_Hilt_Scrap_History> JDJS_WMS_Hilt_Scrap_History { get; set; }
        public virtual DbSet<JDJS_WMS_Hilt_Stock_History> JDJS_WMS_Hilt_Stock_History { get; set; }
        public virtual DbSet<JDJS_WMS_Hilt_Storage_History> JDJS_WMS_Hilt_Storage_History { get; set; }
        public virtual DbSet<JDJS_WMS_Location_Info> JDJS_WMS_Location_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Maintenance_Confirm_Table> JDJS_WMS_Maintenance_Confirm_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Maintenance_Plan_Table> JDJS_WMS_Maintenance_Plan_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Alter_History_Table> JDJS_WMS_Order_Alter_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Blank_Table> JDJS_WMS_Order_Blank_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_DelayTime_Table> JDJS_WMS_Order_DelayTime_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Entry_Table> JDJS_WMS_Order_Entry_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Fixture_Manager_Table> JDJS_WMS_Order_Fixture_Manager_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Guide_Schedu_Table> JDJS_WMS_Order_Guide_Schedu_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Intention_History_Table> JDJS_WMS_Order_Intention_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Process_Info_Table> JDJS_WMS_Order_Process_Info_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Process_Information_Table> JDJS_WMS_Order_Process_Information_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Process_Scheduling_Table> JDJS_WMS_Order_Process_Scheduling_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Process_Tool_Info_Table> JDJS_WMS_Order_Process_Tool_Info_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Queue_Table> JDJS_WMS_Order_Queue_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Schedule_Table> JDJS_WMS_Order_Schedule_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Order_Tool_Prepare_History_table> JDJS_WMS_Order_Tool_Prepare_History_table { get; set; }
        public virtual DbSet<JDJS_WMS_Quality_Confirmation_History_Table> JDJS_WMS_Quality_Confirmation_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Quality_Confirmation_Table> JDJS_WMS_Quality_Confirmation_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Quality_ManualInput_Measurement_Table> JDJS_WMS_Quality_ManualInput_Measurement_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Quality_Onmachine_Measurement_Data> JDJS_WMS_Quality_Onmachine_Measurement_Data { get; set; }
        public virtual DbSet<JDJS_WMS_Quickchangbaseplate_Table> JDJS_WMS_Quickchangbaseplate_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Scan_Operate_History_Table> JDJS_WMS_Scan_Operate_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Secondary_Tooling_Table> JDJS_WMS_Secondary_Tooling_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Staff_Info> JDJS_WMS_Staff_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Borrow_History> JDJS_WMS_Tool_Borrow_History { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_LB_History> JDJS_WMS_Tool_LB_History { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_LifeTime_Management> JDJS_WMS_Tool_LifeTime_Management { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_LifeTimeOver_History_Table> JDJS_WMS_Tool_LifeTimeOver_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Machine_Replaace_History_Table> JDJS_WMS_Tool_Machine_Replaace_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Measurement_Table> JDJS_WMS_Tool_Measurement_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Replace_Reason_Table> JDJS_WMS_Tool_Replace_Reason_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Scrap_History> JDJS_WMS_Tool_Scrap_History { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Shank_Table> JDJS_WMS_Tool_Shank_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Shanks_Specification_Table> JDJS_WMS_Tool_Shanks_Specification_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Standard_Table> JDJS_WMS_Tool_Standard_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Stock_History> JDJS_WMS_Tool_Stock_History { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Storage_History> JDJS_WMS_Tool_Storage_History { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_TypeName_Table> JDJS_WMS_Tool_TypeName_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Users_Login_Info> JDJS_WMS_Tool_Users_Login_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Tool_Verdor_Table> JDJS_WMS_Tool_Verdor_Table { get; set; }
        public virtual DbSet<JDJS_WMS_ToolChangeMessage_Issued_Table> JDJS_WMS_ToolChangeMessage_Issued_Table { get; set; }
        public virtual DbSet<JDJS_WMS_ToolHolder_Table> JDJS_WMS_ToolHolder_Table { get; set; }
        public virtual DbSet<JDJS_WMS_ToolHolder_Tool_Table> JDJS_WMS_ToolHolder_Tool_Table { get; set; }
        public virtual DbSet<JDJS_WMS_ToolHolder_ToolLife_History_Table> JDJS_WMS_ToolHolder_ToolLife_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Users_Login_Info> JDJS_WMS_Users_Login_Info { get; set; }
        public virtual DbSet<JDJS_WMS_Finished_Defective_Product_In_History_Manager> JDJS_WMS_Finished_Defective_Product_In_History_Manager { get; set; }
        public virtual DbSet<JDJS_WMS_Warehouse_InBlank_History_Table> JDJS_WMS_Warehouse_InBlank_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Warehouse_OutBlank_History_Table> JDJS_WMS_Warehouse_OutBlank_History_Table { get; set; }
        public virtual DbSet<JDJS_WMS_Warehouse_InOut_History_Table> JDJS_WMS_Warehouse_InOut_History_Table { get; set; }
    }
}
