//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Staff_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JDJS_WMS_Staff_Info()
        {
            this.JDJS_WMS_Maintenance_Confirm_Table = new HashSet<JDJS_WMS_Maintenance_Confirm_Table>();
            this.JDJS_WMS_Quality_Confirmation_History_Table = new HashSet<JDJS_WMS_Quality_Confirmation_History_Table>();
        }
    
        public int id { get; set; }
        public string staff { get; set; }
        public string position { get; set; }
        public string tel { get; set; }
        public Nullable<int> parentId { get; set; }
        public string users { get; set; }
        public string password { get; set; }
        public string limit { get; set; }
        public string remark { get; set; }
        public string mailbox { get; set; }
        public string orderNumberId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Maintenance_Confirm_Table> JDJS_WMS_Maintenance_Confirm_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JDJS_WMS_Quality_Confirmation_History_Table> JDJS_WMS_Quality_Confirmation_History_Table { get; set; }
    }
}
