//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Order_Fixture_Manager_Table
    {
        public int ID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> FixtureNumber { get; set; }
        public Nullable<int> FixtureFinishPerpareNumber { get; set; }
        public Nullable<int> FixtureAdditionNumber { get; set; }
    
        public virtual JDJS_WMS_Order_Process_Info_Table JDJS_WMS_Order_Process_Info_Table { get; set; }
    }
}
