//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDJS_WMS_Quality_Onmachine_Measurement_Data
    {
        public int ID { get; set; }
        public Nullable<int> CncID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public string SizeName { get; set; }
        public Nullable<double> StandardValue { get; set; }
        public Nullable<double> ToleranceRangeMin { get; set; }
        public Nullable<double> ToleranceRangeMax { get; set; }
        public Nullable<double> Measurements { get; set; }
        public Nullable<int> blankID { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual JDJS_WMS_Device_Info JDJS_WMS_Device_Info { get; set; }
        public virtual JDJS_WMS_Order_Entry_Table JDJS_WMS_Order_Entry_Table { get; set; }
    }
}
